name: Security Scan (Gitleaks)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    name: Scan for Secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2.3.4
